color: orange
fieldLayouts:
  1e40bfec-76e0-47e8-b412-b9ddd57c8592:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T20:54:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4bb47d47-0200-4466-8df6-20829f04a049
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-13T11:01:38+00:00'
            elementCondition: null
            fieldUid: 4a805b89-1a04-4979-8d05-ec829eaf289a # Bild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d14b30f-9bb9-450a-8a56-e4ed6288f829
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-13T10:53:56+00:00'
            elementCondition: null
            fieldUid: 6a3cd148-bc99-4beb-bcc8-046c1ac9e1dc # Kurz-Beschreibung
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58be69f1-c33c-4128-898f-9ba3adecdbb6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-13T10:53:56+00:00'
            elementCondition: null
            fieldUid: 283f2b4b-9210-4126-8d4d-0e3f70da74e9 # HTML
            handle: null
            includeInCards: false
            instructions: null
            label: Beschreibung
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 250ea9f2-ca91-4927-9275-86b046c823a3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-13T10:53:56+00:00'
            elementCondition: null
            fieldUid: 69fc8c65-9336-44e4-a9c5-a62ae50b2b64 # Day
            handle: null
            includeInCards: false
            instructions: null
            label: Tag
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcfb16e9-22cc-4a1f-9095-a6572d591271
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-13T10:53:56+00:00'
            elementCondition: null
            fieldUid: 66a41ec7-003b-4f6a-840b-6565cfffe2db # Time
            handle: null
            includeInCards: false
            instructions: null
            label: Uhrzeit
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa853127-037b-4349-aa21-47c819aa09db
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-13T10:53:56+00:00'
            elementCondition: null
            fieldUid: 5774fc9d-91fc-4367-bc86-ac8c0d4a6cfa # Stage
            handle: null
            includeInCards: false
            instructions: null
            label: Bühne
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a900b60e-6ad5-494c-b738-d22d90777292
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c1db6fc0-97c8-4b11-aadd-07ed50e01a49
        userCondition: null
handle: band
hasTitleField: true
icon: music
name: Band
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
