color: cyan
fieldLayouts:
  b65e70af-5efa-4d15-bfc4-bd74e8cc8344:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-24T19:45:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 74f36895-be38-49f6-9f8e-8177d07760b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-24T19:48:35+00:00'
            elementCondition: null
            fieldUid: 283f2b4b-9210-4126-8d4d-0e3f70da74e9 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ffccb8f-9dfa-4176-80da-66a1e5f4bfbe
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: dadf3e4a-c1d4-41ab-8a68-90576f08ce85
        userCondition: null
handle: faq
hasTitleField: true
icon: life-ring
name: FAQ
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
