color: green
fieldLayouts:
  f4a6ca90-da86-43bc-b7b0-2a1d13530a1e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T20:52:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c783c451-de27-4006-a21a-94d8d57aa3ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-20T11:50:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cdb42f6d-113d-44cd-b2be-64fc96b16ad0 # Show in menu
            handle: null
            includeInCards: false
            instructions: null
            label: 'Im Menü anzeigen'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc9d7c25-059c-4a20-9a7e-5825cdfe02b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T14:01:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fc7e4ae3-3a1d-458a-b8a7-5ffb97d0f9be # Page Contents
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bdfd03b-b50b-4581-916c-b2e50d45f7a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-10T19:12:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b03fb4e7-943f-471d-abf8-5db8bb15fdee # Übergeordnete Seite
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 110db234-43c6-4a52-b00d-141b0cc9b633
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 272cc233-f6e5-4df0-aac4-083552c3e1e4
        userCondition: null
handle: page
hasTitleField: true
icon: page
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
