color: yellow
fieldLayouts:
  05b333ee-0798-4e39-ba9a-29289dcd9757:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-20T18:00:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ba3a1f1b-70b1-465c-a9a8-93de00303810
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-20T18:05:12+00:00'
            elementCondition: null
            fieldUid: 283f2b4b-9210-4126-8d4d-0e3f70da74e9 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4066963f-268e-45a7-b729-40bb23cb0d95
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-20T18:05:12+00:00'
            elementCondition: null
            fieldUid: 88ba550e-be57-48c6-a6ba-403d894e02dd # Ort
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49f7510e-b96e-45de-b2c3-3b9ea8c2bd4c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-20T18:05:12+00:00'
            elementCondition: null
            fieldUid: 4a805b89-1a04-4979-8d05-ec829eaf289a # Bild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28e596d0-6943-4b75-9569-6c16819ca5ca
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: e011e0e1-5788-4a13-9b3b-b9f1cd3d034a
        userCondition: null
handle: programm
hasTitleField: true
icon: icons
name: Programm
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
