color: null
fieldLayouts:
  184031c5-9039-4ff0-9fc2-05fe9067ad61:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-16T18:26:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 50b95225-3e3f-4558-922c-a2c03e5b1b10
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-16T18:28:48+00:00'
            elementCondition: null
            fieldUid: 5d1e74eb-590f-4d9b-83ac-2d1b04415760 # Tickets
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02581fa9-c41b-40c9-ae70-7ebd6c6e8275
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d899d7b0-d7a1-4142-a2de-3cebf3bc6034
        userCondition: null
handle: ticketBlock
hasTitleField: false
icon: ticket
name: 'Ticket Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
