headingLevels:
  - 1
  - 2
  - 3
name: Fancy
options:
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
  image:
    toolbar:
      - 'imageStyle:alignLeft'
      - 'imageStyle:alignCenter'
      - 'imageStyle:alignRight'
      - imageTextAlternative
      - transformImage
  link:
    addTargetToExternalLinks: true
    decorators:
      isButton:
        attributes:
          class: link-button
        label: Button
        mode: manual
      isWitharrow:
        attributes:
          class: link-with-arrow
        label: Pfeil
        mode: manual
    defaultProtocol: 'https://'
    targetOptions: true
toolbar:
  - heading
  - fontSize
  - '|'
  - bold
  - italic
  - underline
  - strikethrough
  - fontColor
  - fontBackgroundColor
  - '|'
  - link
  - insertImage
  - '|'
  - alignment
  - bulletedList
  - numberedList
  - outdent
  - indent
  - horizontalLine
  - '|'
  - insertTable
  - anchor
  - '|'
  - undo
  - redo
  - removeFormat
  - htmlEmbed
  - sourceEditing
