headingLevels:
  - 1
  - 2
  - 3
name: Fancy
options:
  fontColor:
    colors:
      -
        color: 'hsl(0, 0%, 0%)'
        label: Black
      -
        color: 'hsl(0, 0%, 30%)'
        label: 'Dim grey'
      -
        color: 'hsl(0, 0%, 60%)'
        label: Grey
      -
        color: 'hsl(0, 0%, 90%)'
        label: 'Light grey'
      -
        color: 'hsl(0, 0%, 100%)'
        hasBorder: true
        label: White
      -
        color: 'hsl(0, 75%, 60%)'
        label: Red
      -
        color: 'hsl(30, 75%, 60%)'
        label: Orange
      -
        color: 'hsl(60, 75%, 60%)'
        label: Yellow
      -
        color: 'hsl(90, 75%, 60%)'
        label: 'Light green'
      -
        color: 'hsl(120, 75%, 60%)'
        label: Green
      -
        color: 'hsl(150, 75%, 60%)'
        label: Aquamarine
      -
        color: 'hsl(180, 75%, 60%)'
        label: Turquoise
      -
        color: 'hsl(210, 75%, 60%)'
        label: 'Light blue'
      -
        color: 'hsl(240, 75%, 60%)'
        label: Blue
      -
        color: 'hsl(270, 75%, 60%)'
        label: Purple
      -
        color: var(--color-green)
        label: 'PFF Green'
      -
        color: var(--color-blue)
        label: 'PFF Blue'
      -
        color: var(--color-lila)
        label: 'PFF Lila'
      -
        color: var(--color-petrol)
        label: 'PFF Petrol'
      -
        color: var(--color-beige)
        label: 'PFF Beige'
      -
        color: var(--color-linde)
        label: 'PFF Linde'
      -
        color: var(--color-rost)
        label: 'PFF Rost'
    columns: 5
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
  image:
    toolbar:
      - 'imageStyle:alignLeft'
      - 'imageStyle:alignCenter'
      - 'imageStyle:alignRight'
      - imageTextAlternative
      - transformImage
  link:
    addTargetToExternalLinks: true
    decorators:
      isButton:
        attributes:
          class: link-button
        label: Button
        mode: manual
      isWitharrow:
        attributes:
          class: link-with-arrow
        label: Pfeil
        mode: manual
    defaultProtocol: 'https://'
    targetOptions: true
toolbar:
  - heading
  - fontSize
  - '|'
  - bold
  - italic
  - underline
  - strikethrough
  - fontColor
  - fontBackgroundColor
  - '|'
  - link
  - insertImage
  - '|'
  - alignment
  - bulletedList
  - numberedList
  - outdent
  - indent
  - horizontalLine
  - '|'
  - insertTable
  - anchor
  - '|'
  - undo
  - redo
  - removeFormat
  - htmlEmbed
  - sourceEditing
