baseUrl: 'https://craft-cms-demo.ddev.site:8067/de/'
enabled: true
handle: de
hasUrls: true
language: de
name: Deutsch
primary: true
siteGroup: b02cf624-e7cc-4348-8cd6-e7c19d0f8022 # PFF Test
sortOrder: 2
