baseUrl: 'https://craft-cms-demo.ddev.site:8067/fr/'
enabled: '1'
handle: fr
hasUrls: true
language: fr
name: Französisch
primary: false
siteGroup: b02cf624-e7cc-4348-8cd6-e7c19d0f8022 # PFF Test
sortOrder: 3
