altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  95faa7e3-12c7-4e49-99b6-94e6d2285ba6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-13T10:58:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8694300d-b338-483a-8c00-49a3610953fa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3e82dbfd-abd0-454a-95af-3211054bca47
        userCondition: null
fs: uploads
handle: bands
name: Bands
sortOrder: 4
subpath: bands
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: bands/transforms
