columnSuffix: null
handle: blockStyle
instructions: null
name: 'Block Style'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Weiss
        -
          - value
          - white
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Blau
        -
          - value
          - blue
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Grün
        -
          - value
          - green
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Lila
        -
          - value
          - lila
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
