columnSuffix: null
handle: duration
instructions: 'In Minuten'
name: Spieldauer
searchable: false
settings:
  decimals: 0
  defaultValue: 45
  max: 240
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: 5
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
