columnSuffix: null
handle: hihihi
instructions: null
name: hihihi
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - ''
        -
          - value
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
