columnSuffix: null
handle: html
instructions: null
name: Text
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 5a767868-c714-4d14-9887-bc3696500f7b # Fancy
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
