columnSuffix: null
handle: markyy
instructions: null
name: markyy
searchable: false
settings:
  enableLineWrapping: true
  enableSpellChecker: false
  enabledToolbarIconNames:
    - bold
    - italic
    - quote
    - ordered-list
    - unordered-list
    - link
    - image
    - doxter-users
    - doxter-entries
    - doxter-assets
    - doxter-tags
  indentWithTabs: false
  showToolbar: true
  tabSize: 2
translationKeyFormat: null
translationMethod: site
type: verbb\doxter\fields\Doxter
