columnSuffix: null
handle: pageContents
instructions: null
name: 'Page Contents'
searchable: false
settings:
  createButtonLabel: 'Add Block'
  entryTypes:
    - 47d2643e-005f-4d89-918d-f4589848d9cd # Content Block
    - 60b1f1e4-1407-418f-878a-63e8394db8d1 # Code Block (HTML)
    - 438e519b-fd8a-4b06-b94c-e7232e751a58 # Band Block
    - dd5f665e-43be-4d5f-a599-b33983c14f15 # Ticket Block
    - dfa186b3-dd5d-4278-a4f8-3762e9fbb522 # People Block
    - 3b2d278d-b497-4a7e-a2c5-ee5ff555eef1 # Programm Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
