columnSuffix: null
handle: parentpage
instructions: 'Die Seite wird im Untermenü der ausgewählten Seite angezeigt'
name: 'Übergeordnete Seite'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 0
  selectionLabel: 'Übergeordnete Seite auswählen'
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:e096e3ed-d074-4ad7-b8ad-ef51cf15015c' # Pages
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
