columnSuffix: null
handle: time
instructions: null
name: Time
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 5
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
