columnSuffix: null
handle: youtube
instructions: null
name: YouTube
searchable: false
settings:
  maxLength: 1000
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
