dateModified: 1725734112
email:
  fromEmail: info@pff25.ch
  fromName: PFF
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: uploads
    settings:
      path: $CRAFT_WEB_ROOT
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL
meta:
  __names__:
    5a767868-c714-4d14-9887-bc3696500f7b: Fancy # Fancy
    47d2643e-005f-4d89-918d-f4589848d9cd: PageBlock # PageBlock
    60b1f1e4-1407-418f-878a-63e8394db8d1: 'Html Block' # Html Block
    71ad843f-682e-4ae7-bb76-568fe063a92f: 'Public Schema' # Public Schema
    90aa4796-f6b1-42a3-a940-f679702b5518: 'Block Style' # Block Style
    268e30b2-361d-4b81-9e08-483bbc18f966: pageuploads # pageuploads
    283f2b4b-9210-4126-8d4d-0e3f70da74e9: HTML # HTML
    618e4923-3b9b-493f-a1c8-f33aba1400c1: Französisch # Französisch
    679e177d-d0a0-4beb-94c2-d052c3703718: 'Custom CSS' # Custom CSS
    419709be-2d90-4e34-9572-8efb3108bd45: 'Code (HTML)' # Code (HTML)
    a3efe0c5-c237-4131-9622-414a98183477: Italienisch # Italienisch
    b02cf624-e7cc-4348-8cd6-e7c19d0f8022: PFF # PFF
    b2d99a25-b299-4336-87fe-95d042e4935b: Page # Page
    d898aa9b-2eb8-45c2-803d-f1edfcc78cf1: Band # Band
    e0ee82a8-2dc7-46c7-97d6-2a9684e37800: asdf # asdf
    e096e3ed-d074-4ad7-b8ad-ef51cf15015c: Pages # Pages
    f02ed8f0-43c2-4b64-a754-d824ee40e9af: Deutsch # Deutsch
    f1dbea0f-ce16-41ee-ac85-050e80544361: 'PFF Settings' # PFF Settings
    f5da3bdd-1cfa-41af-9e31-02a510ad0e98: 100px # 100px
    f84c51af-ea61-4a1c-96b8-3c40fe10cd57: Simple # Simple
    fc7e4ae3-3a1d-458a-b8a7-5ffb97d0f9be: 'Page Contents' # Page Contents
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  doxter:
    edition: standard
    enabled: true
    schemaVersion: 4.0.0
  language-manager:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0
system:
  edition: solo
  live: true
  name: PFF
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
