dateModified: 1728846389
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - link
      type: native
    -
      heading: Structures
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:529b9251-a976-484a-b9e2-3f7a7beb420c' # Bands
      tableAttributes:
        - status
        - 'field:5774fc9d-91fc-4367-bc86-ac8c0d4a6cfa' # Stage
        - 'field:69fc8c65-9336-44e4-a9c5-a62ae50b2b64' # Day
        - 'field:66a41ec7-003b-4f6a-840b-6565cfffe2db' # Time
        - 'field:4a805b89-1a04-4979-8d05-ec829eaf289a' # Bild
        - uri
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:e096e3ed-d074-4ad7-b8ad-ef51cf15015c' # Pages
      tableAttributes:
        - status
        - dateUpdated
        - uri
      type: native
email:
  fromEmail: info@pff25.ch
  fromName: PFF
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: uploads
    settings:
      path: $CRAFT_WEB_ROOT
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL
meta:
  __names__:
    2d6dc998-a631-473b-aabb-607795249864: 300px # 300px
    2d51e5ff-6165-4ac1-a526-27da48dc6df5: 050px # 050px
    3aa81468-723c-414c-beea-ddee12ffd534: Images # Images
    4a805b89-1a04-4979-8d05-ec829eaf289a: Bild # Bild
    5a767868-c714-4d14-9887-bc3696500f7b: Fancy # Fancy
    6a3cd148-bc99-4beb-bcc8-046c1ac9e1dc: Kurz-Beschreibung # Kurz-Beschreibung
    14e26db9-a9b4-4869-ba41-1d4eea0693b1: 'Band Liste' # Band Liste
    27d8fd23-5b20-4e74-93b9-a10a494c6912: Webseite # Webseite
    30a40700-7cdb-4906-9fb5-1fc34b7e154e: Bands # Bands
    47d2643e-005f-4d89-918d-f4589848d9cd: 'Content Block' # Content Block
    60b1f1e4-1407-418f-878a-63e8394db8d1: 'Code Block (HTML)' # Code Block (HTML)
    66a41ec7-003b-4f6a-840b-6565cfffe2db: Time # Time
    066c0ee4-76c8-42c4-a89a-83cc27c1469d: 'Footer Columns' # Footer Columns
    69fc8c65-9336-44e4-a9c5-a62ae50b2b64: Day # Day
    71ad843f-682e-4ae7-bb76-568fe063a92f: 'Public Schema' # Public Schema
    90aa4796-f6b1-42a3-a940-f679702b5518: 'Block Style' # Block Style
    268e30b2-361d-4b81-9e08-483bbc18f966: 'Page Uploads' # Page Uploads
    283f2b4b-9210-4126-8d4d-0e3f70da74e9: HTML # HTML
    401ee9d8-e854-4a9d-b858-34924ce8a45d: YouTube # YouTube
    438e519b-fd8a-4b06-b94c-e7232e751a58: 'Band Block' # Band Block
    529b9251-a976-484a-b9e2-3f7a7beb420c: Bands # Bands
    618e4923-3b9b-493f-a1c8-f33aba1400c1: Französisch # Französisch
    673f9bd1-3a54-42af-a6b2-e92198b5be01: 'Kontur oben anzeigen' # Kontur oben anzeigen
    679e177d-d0a0-4beb-94c2-d052c3703718: 'Custom CSS' # Custom CSS
    01562c2b-ccc9-49e5-963b-bfb78ae58e77: 800px # 800px
    5774fc9d-91fc-4367-bc86-ac8c0d4a6cfa: Stage # Stage
    384449b0-0e26-4422-b8ff-20b1ed283812: 'Meta Description' # Meta Description
    419709be-2d90-4e34-9572-8efb3108bd45: 'Code (HTML)' # Code (HTML)
    85641352-280c-481a-98ed-9cef22cca8f7: Documents # Documents
    a3efe0c5-c237-4131-9622-414a98183477: Italienisch # Italienisch
    a7a34319-7fc3-4892-9fea-7d13cf4adb1b: Instagram # Instagram
    a668e47c-7099-4611-9500-49855fee3a6b: 648px # 648px
    b02cf624-e7cc-4348-8cd6-e7c19d0f8022: PFF # PFF
    b2d99a25-b299-4336-87fe-95d042e4935b: Page # Page
    cecd9584-5020-49c3-82ae-0a510a7bfe69: 'Content Block' # Content Block
    d293cad1-c4f0-47b4-98c9-bf6c3caaa5ba: Facebook # Facebook
    d898aa9b-2eb8-45c2-803d-f1edfcc78cf1: Band # Band
    df27b7fc-5685-4e0f-8311-29f9dbb5b360: 600px # 600px
    e0ee82a8-2dc7-46c7-97d6-2a9684e37800: 200px # 200px
    e096e3ed-d074-4ad7-b8ad-ef51cf15015c: Pages # Pages
    ea3fca5d-3eda-40c6-9824-ba35f51ef68d: 400px # 400px
    f02ed8f0-43c2-4b64-a754-d824ee40e9af: Deutsch # Deutsch
    f1dbea0f-ce16-41ee-ac85-050e80544361: Settings # Settings
    f5da3bdd-1cfa-41af-9e31-02a510ad0e98: 100px # 100px
    f84c51af-ea61-4a1c-96b8-3c40fe10cd57: Simple # Simple
    f3863ce9-d846-4699-b6b8-7ae0c4b06faf: Spotify # Spotify
    fc7e4ae3-3a1d-458a-b8a7-5ffb97d0f9be: 'Page Contents' # Page Contents
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "@import url('https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,700;1,400;1,700&display=swap');\r\n\r\n:root {\r\n\t--color-green: #027755;\r\n\t--color-blue: #001259;\r\n\t--color-lila: #C092FF;\r\n\t--color-petrol: #30969e;\r\n\t--color-beige: #dbd0af;\r\n\t--color-linde: #d3fd7e;\r\n\t--color-rost: #cd4117;\r\n}\r\n\r\n.ck.ck-content {\r\n\tfont-family: 'Rubik', sans-serif;\r\n}\r\n\r\n.ck.ck-content h1 {\r\n\tfont-weight: normal;\r\n\tfont-size: 36px;\r\n}\r\n.ck.ck-content h2 {\r\n\tfont-weight: normal;\r\n\tfont-size: 22px;\r\n}\r\n.ck.ck-content h3 {\r\n\tfont-size: 16px;\r\n}\r\n\r\n.ck.ck-content a.link-with-arrow::before {\r\n\tcontent: \"→\";\r\n\tmargin-right: 0.4em;\r\n}\r\n\r\n.ck.ck-content a.link-button {\r\n\tbackground: var(--color-blue);\r\n\tcolor: white;\r\n\tpadding: 0.8em 1.5em;\r\n\tborder-radius: 0.5em;\r\n\tdisplay: inline-block;\r\n\tmargin-right: 10px;\r\n}\r\n.ck.ck-content a.link-button:hover {\r\n\tbackground: var(--color-lila);\r\n\tcolor: white;\r\n}\r\n\r\n.ck.ck-content hr {\r\n\tbackground: #3f4d5a;\r\n\theight: 1px;\r\n}"
      cacheBusting: true
      cssFile: ''
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  doxter:
    edition: standard
    enabled: true
    schemaVersion: 4.0.0
  language-manager:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0
  olivemenus:
    edition: standard
    enabled: true
    schemaVersion: 1.1.11
system:
  edition: solo
  live: true
  name: PFF
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
