dateModified: 1726084405
email:
  fromEmail: info@pff25.ch
  fromName: PFF
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: uploads
    settings:
      path: $CRAFT_WEB_ROOT
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL
meta:
  __names__:
    2d6dc998-a631-473b-aabb-607795249864: 300px # 300px
    2d51e5ff-6165-4ac1-a526-27da48dc6df5: 050px # 050px
    3aa81468-723c-414c-beea-ddee12ffd534: Images # Images
    5a767868-c714-4d14-9887-bc3696500f7b: Fancy # Fancy
    47d2643e-005f-4d89-918d-f4589848d9cd: PageBlock # PageBlock
    60b1f1e4-1407-418f-878a-63e8394db8d1: 'Html Block' # Html Block
    066c0ee4-76c8-42c4-a89a-83cc27c1469d: 'Footer Columns' # Footer Columns
    71ad843f-682e-4ae7-bb76-568fe063a92f: 'Public Schema' # Public Schema
    90aa4796-f6b1-42a3-a940-f679702b5518: 'Block Style' # Block Style
    268e30b2-361d-4b81-9e08-483bbc18f966: 'Page Uploads' # Page Uploads
    283f2b4b-9210-4126-8d4d-0e3f70da74e9: HTML # HTML
    618e4923-3b9b-493f-a1c8-f33aba1400c1: Französisch # Französisch
    679e177d-d0a0-4beb-94c2-d052c3703718: 'Custom CSS' # Custom CSS
    01562c2b-ccc9-49e5-963b-bfb78ae58e77: 800px # 800px
    384449b0-0e26-4422-b8ff-20b1ed283812: 'Meta Description' # Meta Description
    419709be-2d90-4e34-9572-8efb3108bd45: 'Code (HTML)' # Code (HTML)
    85641352-280c-481a-98ed-9cef22cca8f7: Documents # Documents
    a3efe0c5-c237-4131-9622-414a98183477: Italienisch # Italienisch
    a668e47c-7099-4611-9500-49855fee3a6b: 648px # 648px
    b02cf624-e7cc-4348-8cd6-e7c19d0f8022: PFF # PFF
    b2d99a25-b299-4336-87fe-95d042e4935b: Page # Page
    cecd9584-5020-49c3-82ae-0a510a7bfe69: 'Content Block' # Content Block
    d898aa9b-2eb8-45c2-803d-f1edfcc78cf1: Band # Band
    df27b7fc-5685-4e0f-8311-29f9dbb5b360: 600px # 600px
    e0ee82a8-2dc7-46c7-97d6-2a9684e37800: 200px # 200px
    e096e3ed-d074-4ad7-b8ad-ef51cf15015c: Pages # Pages
    ea3fca5d-3eda-40c6-9824-ba35f51ef68d: 400px # 400px
    f02ed8f0-43c2-4b64-a754-d824ee40e9af: Deutsch # Deutsch
    f1dbea0f-ce16-41ee-ac85-050e80544361: Settings # Settings
    f5da3bdd-1cfa-41af-9e31-02a510ad0e98: 100px # 100px
    f84c51af-ea61-4a1c-96b8-3c40fe10cd57: Simple # Simple
    fc7e4ae3-3a1d-458a-b8a7-5ffb97d0f9be: 'Page Contents' # Page Contents
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "@import url('https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,700;1,400;1,700&display=swap');\r\n\r\n.ck.ck-content {\r\n\tfont-family: 'Rubik', sans-serif;\r\n}\r\n\r\n.ck.ck-content h1 {\r\n\tfont-weight: normal;\r\n\tfont-size: 36px;\r\n}\r\n.ck.ck-content h2 {\r\n\tfont-weight: normal;\r\n\tfont-size: 22px;\r\n}\r\n.ck.ck-content h3 {\r\n\tfont-size: 16px;\r\n}\r\n\r\n.ck.ck-content a.link-with-arrow::before {\r\n\tcontent: \"→\";\r\n\tmargin-right: 0.4em;\r\n}\r\n\r\n.ck.ck-content hr {\r\n\tbackground: #3f4d5a;\r\n\theight: 1px;\r\n}"
      cacheBusting: true
      cssFile: ''
  doxter:
    edition: standard
    enabled: true
    schemaVersion: 4.0.0
  language-manager:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0
system:
  edition: solo
  live: true
  name: PFF
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
