defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1a8b98e4-c690-4d38-bc3b-1cc9ea82e638 # People
handle: people
maxAuthors: 1
name: People
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  618e4923-3b9b-493f-a1c8-f33aba1400c1: # Französisch
    enabledByDefault: true
    hasUrls: true
    template: people/_entry.twig
    uriFormat: 'people/{slug}'
  a3efe0c5-c237-4131-9622-414a98183477: # Italienisch
    enabledByDefault: true
    hasUrls: true
    template: people/_entry.twig
    uriFormat: 'people/{slug}'
  f02ed8f0-43c2-4b64-a754-d824ee40e9af: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: people/_entry.twig
    uriFormat: 'people/{slug}'
type: channel
