defaultPlacement: end
enableVersioning: true
entryTypes:
  - a9f07671-6678-4af8-81df-68b2715f84dd # Programm
handle: programm
maxAuthors: 1
name: Programm
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre Eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  618e4923-3b9b-493f-a1c8-f33aba1400c1: # Französisch
    enabledByDefault: true
    hasUrls: true
    template: programm/_entry.twig
    uriFormat: 'programm/{slug}'
  a3efe0c5-c237-4131-9622-414a98183477: # Italienisch
    enabledByDefault: true
    hasUrls: true
    template: programm/_entry.twig
    uriFormat: 'programm/{slug}'
  f02ed8f0-43c2-4b64-a754-d824ee40e9af: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: programm/_entry.twig
    uriFormat: 'programm/{slug}'
structure:
  maxLevels: null
  uid: 35775ea6-2fac-4bc2-a432-67a184627003
type: structure
