name: Deploy Website to DEV
run-name: ${{ github.actor }} deployed the website to dev
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Deploy Website
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: pff25.ch
          username: coduzudy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ~/deploy_dev.sh
